micronaut:
  application:
    name: bank-account-application
  server:
    port: 8087
    locale-resolution:
      fixed: en_GB

  jms:
    sqs:
      enabled: true

aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_DEFAULT_REGION}
  sqs:
    endpoint: ${AWS_SQS_ENDPOINT}

jackson:
  mapper:
    accept-case-insensitive-enums: true

app:
  aws:
    sqs:
      card-application-queue-name: card-application
      bank-account-created-queue-name: bank-account-created
