server:
  port: 8080

spring:
  application:
    name: card-applications

  kafka:
    bootstrap-servers: localhost:9093, localhost:9094, localhost:9095
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  jackson:
    mapper:
      accept-case-insensitive-enums: true

  level:
    root: debug
    sql: info
    web: info

app:
  kafka:
    card-application-topic: card-application
