server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3206/cards_db
    username: admin
    password: sB6mbtzNHmCQI4eN4yLo
    driverClassName: com.mysql.cj.jdbc.Driver

  kafka:
    bootstrap-servers: localhost:9093, localhost:9094, localhost:9095

  flyway:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

  jpa:
    hibernate:
      ddl-auto: none

  jackson:
    mapper:
      accept-case-insensitive-enums: true

  level:
    root: debug
    sql: info
    web: info

